---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-pass
type: Opaque
data:
  password: YWRtaW4=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  mysql.cnf: |
   [client]
   port        = 3306
   socket      = 
   [mysqld_safe]
   socket      = 
   nice        = 0
   [mysqld]
   # * Basic Settings
   user        = mysql
   pid-file    = /var/run/mysqld/mysqld.pid
   socket      = /var/run/mysqld/mysqld.sock
   port        = 3306
   basedir     = /usr
   datadir     = /var/lib/mysql
   tmpdir      = /tmp
   lc-messages-dir = /usr/share/mysql
   skip-external-locking
   sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
   key_buffer_size     = 16M
   max_allowed_packet  = 16M
   thread_stack        = 258K
   thread_cache_size       = 8
   myisam_recover_options  = BACKUP
   max_connections         = 50
   query_cache_limit = 2M
   query_cache_size        = 15M
   log_error = /var/log/mysql/error.log
   [mysqldump]
   quick
   quote-names
   max_allowed_packet  = 16M
   [mysql]
   local-infile=1
   [isamchk]
   key_buffer_size     = 8M
---
apiVersion: v1
kind: Pod
metadata:
  name: k8s-mysql
  labels:
    name: lbl-k8s-mysql
spec:
  containers:
  - name: mysql
    image: mysql:latest
    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysql-pass
          key: password
    ports:
    - name: mysql
      containerPort: 3306
      protocol: TCP
    volumeMounts:
    - name: mysql-cnf
      mountPath: /etc/mysql
  volumes:
  - name: mysql-cnf
    configMap:
      name: mysql-config
