apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: nginx-pod-lbl
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - name: nginx
      containerPort: 80
      protocol: TCP
    volumeMounts:
    - name: nginx-conf
      mountPath: /etc/nginx
  volumes:
  - name: nginx-conf
    configMap:
      name: nginx-conf
